estimation_active: false
camera_process: false
camera_GUI: false
octomap: true
visualization: true
csv_writer: false

generator:
  start_capacity: 150
  start_lenght: 3.0
  end_lenght: 27.0

  uniform:
    range: 1.0    
  lines:
    number_lines: 200
  random:
    capacity_lines: 200
    number_iterations: 3000
    start_dist_weight: 0.2
    end_dist_weight:  1.0

sample_filter:
  #vizualization
  draw_limit_dataset: 400
  #dataset size
  dataset_limit : 1500 #menej zdrojov radiacie, mensia hodnota , For AVG fitler around 700
  # /* source Estimations*/
  estimation_limit: 300
  estimation_dist: 0.9
  estimation_min_group_size: 15
  # /* Filters  */
   # /*cicleFilter*/
  threshold_distance : 0.5
  threshold_hit : 0
  hit_score : 1
  miss_score : -4
  hit_position : 0.5
  miss_position : 0.9
  # /*SumNumFilter*/
  nearest_sum_n : 2
  queue_sum_n : 1
  #/*Average Filter*/
  input_coef_avg_best : 0.1 
  output_size_avg_best : 0  
   # /*RandomFilter*/
  random_sample_coef : 0.4 
    #/*WorstOfNumFilter*/
  input_size_avg_worst : 10     #same as dataset size
  output_coef_avg_worst : 0 

image_filter:
  threshold_shift: 135
  size_threshold: 360
  dilation: 0
  dilation_size: 1
  delta_distance: 25
  resize_image: 50
  show_edges: 0
