generator:
  start_capacity: 150
  start_lenght: 3.0
  end_lenght: 25.0

  uniform:
    range: 1.0    
  lines:
    number_lines: 200
  random:
    capacity_lines: 200
    number_iterations: 3000
    start_dist_weight: 0.2
    end_dist_weight:  1.0

sample_filter:
  draw_limit_dataset: 400
  dataset_limit : 1000
  # /* source Estimations*/
  estimation_limit: 400
  estimation_dist: 0.6
  estimation_min_group_size: 10
  # /* Filters  */
   # /*cicleFilter*/
  threshold_distance : 0.5
  threshold_hit : 0
  hit_score : 5
  miss_score : -1
  hit_position : 0.7
  miss_position : 0.95
  # /*SumNumFilter*/
  nearest_sum_n : 2
  queue_sum_n : 3
  #/*BestOfNumFilter*/
  input_coef_avg_best : 0.4 
  output_size_avg_best : 1    
   # /*RandomFilter*/
  random_sample_coef : 0.33 
    #/*WorstOfNumFilter*/
  input_size_avg_worst : 10     
  output_coef_avg_worst : 0.4  

image_filter:
  threshold_shift: 135
  size_threshold: 360
  dilation: 0
  dilation_size: 1
  delta_distance: 25
  resize_image: 50
  show_edges: 0